"""Module config: DC项目列表 (DcProjectListAction)"""
from __future__ import annotations
from new_mcp_servers.core.config import EnumField, FieldLabel, FilterDef, ModuleConfig

_BASE_PATH = "/DcProjectListAction"

dc_project = ModuleConfig(
    name="query_dc_project_list",
    display_name="DC项目列表",
    description="查询 DC 项目列表，按 scope 路由到默认或紧急案件视图。",
    endpoint=_BASE_PATH + "/listQueryMyDc",
    scope_endpoints={
        "default": _BASE_PATH + "/listQueryMyDc",
        "urgent": _BASE_PATH + "/listQueryMyDc",
    },
    scope_datatype_defaults={
        "default": "listView",
        "urgent": "urgent",
    },
    extra_params=["date_enums", "finish_date_enums", "start_up_date_enums", "include_raw"],
    filters=[
        FilterDef("apply_certificate_date", "dp.apply_certificate_date", "实际交付日期", "="),
        FilterDef("arrival_date_start", "dp.arrival_date", "到样日期起", ">=", is_date_range=True),
        FilterDef("arrival_date_end", "dp.arrival_date", "到样日期止", "<=", is_date_range=True),
        FilterDef("assistant_name", "ap.PERSON_NAME", "销售", "like"),
        FilterDef("bstatus", "dp.BSTATUS", "案件状态", "=",
                  enums={2: "未开始", 3: "进行中", 1: "试验完成报告未出", 4: "试验完成报告已出", 5: "试验暂停中", 6: "试验终止", 7: "结案", 0: "未开案", 8: "取消", 9: "未分配", 10: "实验室退回"}),
        FilterDef("bstatus_project", "sso.bstatus_project", "合同开案状态", "=",
                  enums={20: "未开案", 25: "未开始", 30: "案件进行中", 40: "试验完成报告未出", 45: "试验完成报告已出", 50: "结案", 55: "异常"}),
        FilterDef("closed_date_start", "dp.closed_date", "结案日期起", ">=", is_date_range=True),
        FilterDef("closed_date_end", "dp.closed_date", "结案日期止", "<=", is_date_range=True),
        FilterDef("delivery_name", "ap2.PERSON_NAME", "交付专员", "like"),
        FilterDef("dept_id", "dp.dept_id", "负责实验室", "="),
        FilterDef("dm_report_require_report_type", "drr.report_type", "要求报告标识", "=",
                  enums={"not": "无标志", "cnas": "CNAS标志", "a2la": "A2LA标志", "cma": "CMA标志", "cnas/a2la": "CNAS+A2LA", "not/cma": "CNAS+CMA", "nvlap": "NVLAP标志", "cnas/nvlap": "CNAS+NVLAP", "other": "其它"}),
        FilterDef("engineer_name", "ap1.PERSON_NAME", "项目工程师", "like"),
        FilterDef("fast_search", "fastSearch", "快速搜索", "like"),
        FilterDef("finish_date", "dp.closed_date", "结束日期", "<=", is_date_range=True),
        FilterDef("finish_date_end", "dp.closed_date", "结束日期止", "<=", is_date_range=True),
        FilterDef("item_category", "ssod.item_category", "服务类别", "="),
        FilterDef("organization_name", "ao.organization_name", "报价公司", "like"),
        FilterDef("plan_delivery_date", "dp.plan_delivery_date", "计划交付日期", "="),
        FilterDef("plan_end_date_start", "dp.plan_end_date", "计划结束日期起", ">=", is_date_range=True),
        FilterDef("plan_end_date_end", "dp.plan_end_date", "计划结束日期止", "<=", is_date_range=True),
        FilterDef("product_model", "sso.sample_model_cn", "样品型号", "like"),
        FilterDef("product_name", "sso.sample_name_cn", "样品名称", "like"),
        FilterDef("project_consignor_name", "ac.CUSTOMER_NAME_CN", "合同方", "like"),
        FilterDef("project_name", "dp.service_pro_name", "负责项目", "like"),
        FilterDef("project_no", "dp.PROJECT_NO", "开案号", "like"),
        FilterDef("rstatus", "dp.rstatus", "单据状态", "=",
                  enums={0: "已作废", 1: "已审核", 2: "暂存", 3: "等待重新审批", 4: "审批中"}),
        FilterDef("sales_order_no", "sso.sales_order_no", "销售合同", "like"),
        FilterDef("service_item_desc", "sso.service_item_desc", "服务项目", "like"),
        FilterDef("service_pro_standard", "dp.service_pro_standard", "依据标准库", "like"),
        FilterDef("start_up_date", "dp.CREATE_ON", "开案日期截止", "<=", is_date_range=True),
        FilterDef("start_up_date_end", "dp.CREATE_ON", "开案日期止", "<=", is_date_range=True),
        FilterDef("terminal_authorization_customer", "sso.terminal_authorization_customer_name", "授权终端", "like"),
        # ── 候选 filter ──
        FilterDef("actuality_finish_date_start", "actualityFinishDate", "合同结束日期起", ">=", is_date_range=True),
        FilterDef("actuality_finish_date_end", "actualityFinishDate", "合同结束日期止", "<=", is_date_range=True),
        FilterDef("apply_certificate_date_start", "applyCertificateDate", "递交证书日期起", ">=", is_date_range=True),
        FilterDef("apply_certificate_date_end", "applyCertificateDate", "递交证书日期止", "<=", is_date_range=True),
        FilterDef("assignment_date_start", "assignmentDate", "分配日期起", ">=", is_date_range=True),
        FilterDef("assignment_date_end", "assignmentDate", "分配日期止", "<=", is_date_range=True),
        FilterDef("certificate_amt_local", "certificateAmtLocal", "规费B", "like"),
        FilterDef("certification_case_type", "certificationCaseType", "是否认证案件", "like"),
        FilterDef("confirm_standard", "confirmStandard", "确认标准", "like"),
        FilterDef("consumable_amt_local", "consumableAmtLocal", "耗材支出", "like"),
        FilterDef("create_on_start", "createOn", "创建日期起", ">=", is_date_range=True),
        FilterDef("create_on_end", "createOn", "创建日期止", "<=", is_date_range=True),
        FilterDef("customer_level", "customerLevel", "客户级别", "like"),
        FilterDef("day_count", "dayCount", "案件耗时(天)", "like"),
        FilterDef("deduction_amt_local", "deductionAmtLocal", "税费进项抵扣", "like"),
        FilterDef("delivery_dept_name", "deliveryDeptName", "交付部门", "like"),
        FilterDef("delivery_name2", "assistantName2", "交付专员(候选)", "like"),
        FilterDef("department_name", "departmentName", "负责实验室", "like"),
        FilterDef("draft_report_date_start", "draftReportDate", "草稿报告日期起", ">=", is_date_range=True),
        FilterDef("draft_report_date_end", "draftReportDate", "草稿报告日期止", "<=", is_date_range=True),
        FilterDef("end_date_start", "endDate", "实际结案起", ">=", is_date_range=True),
        FilterDef("end_date_end", "endDate", "实际结案止", "<=", is_date_range=True),
        FilterDef("expiration_reminder", "expirationReminder", "到期提醒", "like"),
        FilterDef("external_brand", "externalBrand", "商标", "like"),
        FilterDef("external_certificate_agency", "externalCertificateAgency", "发证机构", "like"),
        FilterDef("external_certificate_no", "externalCertificateNo", "认证号", "like"),
        FilterDef("gross_profit_margin", "grossProfitMargin", "毛利率%", "like"),
        FilterDef("manufacturer_name_cn", "manufacturerNameCn", "制造商(中)", "like"),
        FilterDef("manufacturer_name_en", "manufacturerNameEn", "制造商(英)", "like"),
        FilterDef("message_notification", "messageNotification", "留言通知", "like"),
        FilterDef("net_price2_local", "netPrice2Local", "净值", "like"),
        FilterDef("outsource_amt_local", "outsourceAmtLocal", "外包费", "like"),
        FilterDef("overdue_days", "overdueDays", "逾期天数", "like"),
        FilterDef("plan_delivery_date_start", "planDeliveryDate", "计划交付日期起", ">=", is_date_range=True),
        FilterDef("plan_delivery_date_end", "planDeliveryDate", "计划交付日期止", "<=", is_date_range=True),
        FilterDef("project_progress_history", "projectProgressHistory", "案件进度", "like"),
        FilterDef("report_label", "actReportType", "实际报告标识", "like"),
        FilterDef("report_nos", "reportNos", "报告号", "like"),
        FilterDef("sale_amount_with_tax_local", "saleAmountWithTaxLocal", "案件金额", "like"),
        FilterDef("sales_remark", "salesRemark", "内部备注", "like"),
        FilterDef("service_items", "projectName", "负责项目", "like"),
        FilterDef("service_pro_name", "serviceProName", "项目描述", "like"),
        FilterDef("so_distribute_code", "soDistributeCode", "项目代码", "like"),
        FilterDef("start_up_date_start", "startUpDate", "开案日期起", ">=", is_date_range=True),
        FilterDef("sum_other_amt_local", "sumOtherAmtLocal", "规费A", "like"),
        FilterDef("tax_amt_local", "taxAmtLocal", "税费", "like"),
    ],
    field_labels={
        "projectNo": FieldLabel("project_no", "开案号"),
        "createOn": FieldLabel("create_on", "创建日期"),
        "organizationName": FieldLabel("organization_name", "报价公司"),
        "salesOrderNo": FieldLabel("sales_order_no", "销售合同"),
        "actualityFinishDate": FieldLabel("actuality_finish_date", "合同结束日期"),
        "departmentName": FieldLabel("department_name", "负责实验室"),
        "assignmentDate": FieldLabel("assignment_date", "分配日期"),
        "arrivalDate": FieldLabel("arrival_date", "开案日期"),
        "engineerName": FieldLabel("engineer_name", "项目工程师"),
        "projectConsignorName": FieldLabel("project_consignor_name", "合同方"),
        "expirationReminder": FieldLabel("expiration_reminder", "到期提醒"),
        "startUpDate": FieldLabel("start_up_date", "开案日期"),
        "assistantName": FieldLabel("assistant_name", "销售"),
        "productName": FieldLabel("product_name", "样品名称"),
        "deliveryName": FieldLabel("delivery_name", "交付专员"),
        "productModel": FieldLabel("product_model", "样品型号"),
        "dmReportRequireReportType": FieldLabel("dm_report_require_report_type", "要求报告标识"),
        "serviceItems": FieldLabel("service_items", "负责项目"),
        "bstatus": FieldLabel("bstatus", "案件状态"),
        "terminalAuthorizationCustomer": FieldLabel("terminal_authorization_customer", "授权终端"),
        "serviceProName": FieldLabel("service_pro_name", "项目描述"),
        "soDistributeCode": FieldLabel("so_distribute_code", "项目代码"),
        "itemCategory": FieldLabel("item_category", "服务类别"),
        "serviceProStandard": FieldLabel("service_pro_standard", "依据标准库"),
        "reportLabel": FieldLabel("report_label", "实际报告标识"),
        "projectProgressHistory": FieldLabel("project_progress_history", "案件进度"),
        "customerLevel": FieldLabel("customer_level", "客户级别"),
        "messageNotification": FieldLabel("message_notification", "留言通知"),
        "confirmStandard": FieldLabel("confirm_standard", "确认标准"),
        "endDate": FieldLabel("end_date", "实际结案"),
        "planEndDate": FieldLabel("plan_end_date", "要求结案"),
        "closedDate": FieldLabel("closed_date", "实际结案"),
        "saleAmountWithTaxLocal": FieldLabel("sale_amount_with_tax_local", "案件金额"),
        "planDeliveryDate": FieldLabel("plan_delivery_date", "计划交付日期"),
        "applyCertificateDate": FieldLabel("apply_certificate_date", "递交申请证书时间"),
        "outsourceAmtLocal": FieldLabel("outsource_amt_local", "外包费"),
        "salesRemark": FieldLabel("sales_remark", "内部备注"),
        "overdueDays": FieldLabel("overdue_days", "逾期天数"),
        "draftReportDate": FieldLabel("draft_report_date", "草稿报告完成日期"),
        "deliveryName2": FieldLabel("delivery_name2", "交付专员"),
        "deliveryDeptName": FieldLabel("delivery_dept_name", "交付部门"),
        "externalCertificateAgency": FieldLabel("external_certificate_agency", "发证机构"),
        "externalBrand": FieldLabel("external_brand", "商标"),
        "dayCount": FieldLabel("day_count", "案件耗时(天)"),
        "externalCertificateNo": FieldLabel("external_certificate_no", "认证号"),
        "reportNos": FieldLabel("report_nos", "报告号"),
        "sumOtherAmtLocal": FieldLabel("sum_other_amt_local", "规费A"),
        "certificationCaseType": FieldLabel("certification_case_type", "是否认证案件"),
        "manufacturerNameCn": FieldLabel("manufacturer_name_cn", "制造商(中)"),
        "certificateAmtLocal": FieldLabel("certificate_amt_local", "规费B"),
        "manufacturerNameEn": FieldLabel("manufacturer_name_en", "制造商(英)"),
        "consumableAmtLocal": FieldLabel("consumable_amt_local", "耗材支出"),
        "deductionAmtLocal": FieldLabel("deduction_amt_local", "税费进项抵扣"),
        "taxAmtLocal": FieldLabel("tax_amt_local", "税费"),
        "netPrice2Local": FieldLabel("net_price2_local", "净值"),
        "grossProfitMargin": FieldLabel("gross_profit_margin", "毛利率(%)"),
    },
    enum_fields={
        "bstatus": EnumField({2: "未开始", 3: "进行中", 1: "试验完成报告未出", 4: "试验完成报告已出", 5: "试验暂停中", 6: "试验终止", 7: "结案", 0: "未开案", 8: "取消", 9: "未分配", 10: "实验室退回"}),
        "bstatus_project": EnumField({20: "未开案", 25: "未开始", 30: "案件进行中", 40: "试验完成报告未出", 45: "试验完成报告已出", 50: "结案", 55: "异常"}),
        "dm_report_require_report_type": EnumField({"not": "无标志", "cnas": "CNAS标志", "a2la": "A2LA标志", "cma": "CMA标志", "cnas/a2la": "CNAS+A2LA", "not/cma": "CNAS+CMA", "nvlap": "NVLAP标志", "cnas/nvlap": "CNAS+NVLAP", "other": "其它"}),
        "rstatus": EnumField({0: "已作废", 1: "已审核", 2: "暂存", 3: "等待重新审批", 4: "审批中"}),
    },
)
