"""Module config: 收费单列表 (DmTestChargeListAction)"""
from __future__ import annotations
from new_mcp_servers.core.config import EnumField, FieldLabel, FilterDef, ModuleConfig

_BASE_PATH = "/DmTestChargeListAction"

dm_test_charge = ModuleConfig(
    name="query_dmtestchargelistaction",
    display_name="收费单",
    description="查询收费单列表。",
    endpoint=_BASE_PATH + "/listQuery",
    scope_endpoints={
        "default": _BASE_PATH + "/listQuery",
        "all": _BASE_PATH + "/listQueryAll",
        "gen": _BASE_PATH + "/listQueryGen",
        "project": _BASE_PATH + "/listQueryProject",
        "rf": _BASE_PATH + "/listQueryRf",
        "sso": _BASE_PATH + "/listQuerySSO",
        "temp": _BASE_PATH + "/listQueryTemp",
        "temp_rf": _BASE_PATH + "/listQueryTempRf",
    },
    scope_svars={
        "default": {"operation": "operation", "showAmount": "showAmount"},
    },
    scope_datatype_defaults={
        "default": "mainView",
        "all": "weekView",
        "rf": "mainView",
    },
    extra_params=["include_raw"],
    filters=[
        FilterDef("bstatus", "dtc.bstatus", "收费单状态", "=", enums={1: "未转销售合同", 4: "已转销售合同", 5: "已收款", 0: "已作废"}),
        FilterDef("charge_no", "charge_no", "收费单编号", "like"),
        FilterDef("contract_no", "sso.sales_order_no", "合同编号", "like"),
        FilterDef("customer_name", "tcp.consignor_name_cn", "客户", "like"),
        FilterDef("entrusted_project_no", "dp.project_no", "案件编号", "like"),
        FilterDef("fast_search", "fastSearch", "快速搜索", "like"),
        FilterDef("item_no", "tcp.project_no", "项目名", "like"),
        FilterDef("modular_type", "dtc.modular_type", "模块类型", "="),
        FilterDef("order_date", "order_date", "开单日期", "="),
        FilterDef("order_date2", "order_date", "开单日期(备)", "="),
        FilterDef("order_date_start", "order_date", "开单日期起", ">=", is_date_range=True),
        FilterDef("order_name", "ap.person_name", "打单人", "like"),
        FilterDef("plan_pay_type", "dtc.plan_pay_type", "计划付款方式", "=", enums={1: "现金", 2: "转账", 3: "月结", 4: "微信支付"}),
        FilterDef("saler_name", "ap1.person_name", "负责销售", "like"),
        FilterDef("sample_model", "dtce.emcTemporarySampleModel", "样品型号", "like"),
        FilterDef("sample_name", "dtce.emcTemporarySampleName", "样品名称", "like"),
        FilterDef("sign_status", "dtc.sign_status", "签字状态", "="),
        FilterDef("test_requirement", "tcp.test_requirement", "试验类型", "="),
        FilterDef("bill_biz_typ_e_id", "billBizTypeId", "所属模块(候选)", "="),
        FilterDef("bill_biz_type_id", "billBizTypeId", "所属模块", "="),
        FilterDef("customer_contact", "customerContact", "客户联系人", "like"),
        FilterDef("docket_name", "docketName", "打单人(候选)", "like"),
        FilterDef("emc_temporary_sample_model", "emcTemporarySampleModel", "试验样品型号", "like"),
        FilterDef("emc_temporary_sample_name", "emcTemporarySampleName", "试验样品名称", "like"),
        FilterDef("locale_customer_engineer", "localeCustomerEngineer", "现场客户工程师", "like"),
        FilterDef("locations", "locations", "试验场地", "like"),
        FilterDef("order_date_end", "orderDate", "开单日期止", "<=", is_date_range=True),
        FilterDef("send_email_status", "sendEmailStatus", "发送情况", "like"),
        FilterDef("test_date", "testDate", "试验日期", "like"),
        FilterDef("test_engineer_name", "testEngineerName", "试验人员", "like"),
        FilterDef("test_item", "testItem", "试验项目", "like"),
        FilterDef("test_time", "testTime", "试验时长", "like"),
        FilterDef("total_amt", "totalAmt", "总计", "like"),
        FilterDef("total_chargeable_duration", "totalChargeableDuration", "应收费时长", "like"),
        FilterDef("total_free_duration", "totalFreeDuration", "免单时长", "like"),
        FilterDef("total_hours", "totalHours", "收费单时长", "like"),
    ],
    field_labels={
        "billBizTypeId": FieldLabel("bill_biz_type_id", "所属模块"),
        "chargeNo": FieldLabel("charge_no", "收费单编号"),
        "contractNo": FieldLabel("contract_no", "合同编号"),
        "orderDate": FieldLabel("order_date", "开单日期"),
        "docketName": FieldLabel("docket_name", "打单人"),
        "signStatus": FieldLabel("sign_status", "签字状态"),
        "customerName": FieldLabel("customer_name", "客户"),
        "bstatus": FieldLabel("bstatus", "收费单状态"),
        "customerContact": FieldLabel("customer_contact", "客户联系人"),
        "testRequirement": FieldLabel("test_requirement", "试验类型"),
        "itemNo": FieldLabel("item_no", "项目名/现场试验号"),
        "entrustedProjectNo": FieldLabel("entrusted_project_no", "案件编号"),
        "sampleName": FieldLabel("sample_name", "样品名称"),
        "sendEmailStatus": FieldLabel("send_email_status", "发送情况"),
        "localeCustomerEngineer": FieldLabel("locale_customer_engineer", "现场客户测试工程师"),
        "sampleModel": FieldLabel("sample_model", "样品型号"),
        "locations": FieldLabel("locations", "试验场地"),
        "hasAttachment": FieldLabel("has_attachment", "是否有附件"),
        "testItem": FieldLabel("test_item", "试验项目"),
        "planPayType": FieldLabel("plan_pay_type", "计划付款方式"),
        "testDate": FieldLabel("test_date", "试验日期"),
        "testEngineerName": FieldLabel("test_engineer_name", "试验人员"),
        "emcTemporarySampleName": FieldLabel("emc_temporary_sample_name", "试验样品名称"),
        "testTime": FieldLabel("test_time", "试验时长(H)"),
        "emcTemporarySampleModel": FieldLabel("emc_temporary_sample_model", "试验样品型号"),
        "salerName": FieldLabel("saler_name", "负责销售"),
        "totalFreeDuration": FieldLabel("total_free_duration", "免单时长(H)"),
        "totalChargeableDuration": FieldLabel("total_chargeable_duration", "应收费时长(H)"),
        "totalHours": FieldLabel("total_hours", "收费单时长(H)"),
        "totalAmt": FieldLabel("total_amt", "总计"),
    },
    enum_fields={
        "bill_biz_type_id": EnumField({"lab06_01": "案件项目", "lab06_02": "现场收费单", "lab07_01": "案件项目", "lab07_02": "现场收费单"}),
        "bstatus": EnumField({1: "未转销售合同", 4: "已转销售合同", 5: "已收款", 0: "已作废"}),
        "plan_pay_type": EnumField({1: "现金", 2: "转账", 3: "月结", 4: "微信支付"}),
    },
)
