"""Module config: 现场试验收费单 (EmcTemporaryTestListAction)"""
from __future__ import annotations
from new_mcp_servers.core.config import EnumField, FieldLabel, FilterDef, ModuleConfig

_BASE_PATH = "/EmcTemporaryTestListAction"

emc_temporary_test = ModuleConfig(
    name="query_emctemporarytestlistaction",
    display_name="现场试验记录",
    description="查询现场试验记录列表。",
    endpoint=_BASE_PATH + "/listQuery",
    scope_endpoints={
        "default": _BASE_PATH + "/listQuery",
        "all": _BASE_PATH + "/listQueryForAll",
        "entrust": _BASE_PATH + "/listQueryEntrust",
        "listqueryentrust": _BASE_PATH + "/listQueryEntrust",
        "for_all": _BASE_PATH + "/listQueryForAll",
        "listqueryforall": _BASE_PATH + "/listQueryForAll",
        "cockpit": _BASE_PATH + "/listQueryForCockpit01",
        "listqueryforcockpit01": _BASE_PATH + "/listQueryForCockpit01",
        "dm": _BASE_PATH + "/listQueryForDM",
        "dept": _BASE_PATH + "/listQueryForDeptSaler",
        "gen": _BASE_PATH + "/listQueryForGen",
        "locale": _BASE_PATH + "/listQueryForLocale",
        "listqueryforlocale": _BASE_PATH + "/listQueryForLocale",
        "mine": _BASE_PATH + "/listQueryForMe",
        "op": _BASE_PATH + "/listQueryForOp",
        "safety": _BASE_PATH + "/listQueryForSFY",
        "saler": _BASE_PATH + "/listQueryForSaler",
        "listqueryforsaler": _BASE_PATH + "/listQueryForSaler",
    },
    scope_svars={
        "default": {"operation": "operation"},
        "all": {"modularType": "emc"},
    },
    scope_datatype_defaults={
        "default": "newDate",
        "dept": "total",
        "dm": "my",
        "entrust": "my",
        "for_all": "total",
        "gen": "newDate",
        "mine": "total",
        "safety": "my",
    },
    extra_params=["include_raw"],
    filters=[
        FilterDef("charge_bstatus", "dtc.bstatus", "收费单状态", "=",
                  enums={1: "未转销售合同", 4: "已转销售合同", 5: "已收款", 0: "已作废"}),
        FilterDef("charge_no", "dtc.charge_no", "收费单编号", "like"),
        FilterDef("consignor_name_cn", "etp.consignor_name_cn", "客户", "like"),
        FilterDef("create_on2", "ett.create_on", "创建日期截止", "<=", is_date_range=True),
        FilterDef("create_on_start", "ett.create_on", "创建日期起", ">=", is_date_range=True),
        FilterDef("create_on_end", "ett.create_on", "创建日期止", "<=", is_date_range=True),
        FilterDef("customer_name", "etp.consignor_contacts_cn", "客户联系人", "like"),
        FilterDef("entrusted_project_no", "etp.entrusted_project_no", "案件编号", "like"),
        FilterDef("fast_search", "fastSearch", "快速搜索", "like"),
        FilterDef("location_id", "tdl.location_id", "试验场地", "="),
        FilterDef("manager1", "ap.PERSON_NAME", "试验人员", "like"),
        FilterDef("order_description", "ett.order_description", "收费单说明", "=",
                  enums={1: "需要", 2: "不需要"}),
        FilterDef("order_status", "ett.order_status", "开单状态", "=",
                  enums={0: "未开单", 1: "已开单"}),
        FilterDef("product_model", "etp.sample_model_cn", "样品型号", "like"),
        FilterDef("product_name", "etp.sample_name_cn", "样品名称", "like"),
        FilterDef("project_no", "etp.projectNo", "试验项目编号", "like"),
        FilterDef("service_pro_name", "ett.test_item", "试验项目", "like"),
        FilterDef("terminal_authorization_customer", "etp.terminal_authorization_customer", "授权终端客户", "like"),
        FilterDef("charge_date", "chargeDate", "收费单日期", "like"),
        FilterDef("charge_person", "chargePerson", "收费单人", "like"),
        FilterDef("charge_time", "chargeTime", "收费单时长", "like"),
        FilterDef("docket_person", "docketPerson", "打单人", "like"),
        FilterDef("engineer_name", "engineerName", "试验人员(候选)", "like"),
        FilterDef("locale_customer_engineer", "localeCustomerEngineer", "现场客户工程师", "like"),
        FilterDef("locations", "locations", "试验场地(候选)", "like"),
        FilterDef("no_order_description", "noOrderDescription", "无需收费单原因", "like"),
        FilterDef("project_no_main", "projectNoMain", "现场试验编号", "like"),
        FilterDef("remark", "remark", "项目备注", "like"),
        FilterDef("saler_person_name", "salerPersonName", "负责销售", "like"),
        FilterDef("sample_model_cn", "sampleModelCn", "样品型号(候选)", "like"),
        FilterDef("sample_name_cn", "sampleNameCn", "样品名称(候选)", "like"),
        FilterDef("sample_no", "sampleNo", "样品编号", "like"),
        FilterDef("test_charge_no", "testChargeNo", "收费单编号(候选)", "like"),
        FilterDef("test_date", "testDate", "试验日期", "like"),
        FilterDef("test_item", "testItem", "试验项目(候选)", "like"),
        FilterDef("test_requirement", "testRequirement", "试验类型", "=",
                  enums={"scene": "现场测试", "rectification": "案件整改/重测", "caseTest": "案件测试"}),
        FilterDef("test_time", "testTime", "试验时长", "like"),
    ],
    field_labels={
        "projectNoMain": FieldLabel("project_no_main", "现场试验编号"),
        "projectNo": FieldLabel("project_no", "试验项目编号"),
        "createOn": FieldLabel("create_on", "创建日期"),
        "consignorNameCn": FieldLabel("consignor_name_cn", "客户"),
        "localeCustomerEngineer": FieldLabel("locale_customer_engineer", "现场客户测试工程师"),
        "locations": FieldLabel("locations", "试验场地"),
        "testItem": FieldLabel("test_item", "试验项目"),
        "testRequirement": FieldLabel("test_requirement", "试验类型"),
        "engineerName": FieldLabel("engineer_name", "试验人员"),
        "testDate": FieldLabel("test_date", "试验日期"),
        "orderDescription": FieldLabel("order_description", "收费单说明"),
        "orderStatus": FieldLabel("order_status", "开单状态"),
        "noOrderDescription": FieldLabel("no_order_description", "无需收费单原因"),
        "entrustedProjectNo": FieldLabel("entrusted_project_no", "案件编号"),
        "testTime": FieldLabel("test_time", "试验时长"),
        "testChargeNo": FieldLabel("test_charge_no", "收费单编号"),
        "chargeBstatus": FieldLabel("charge_bstatus", "收费单状态"),
        "chargeTime": FieldLabel("charge_time", "收费单时长"),
        "chargeDate": FieldLabel("charge_date", "收费单日期"),
        "chargePerson": FieldLabel("charge_person", "收费单人"),
        "docketPerson": FieldLabel("docket_person", "打单人"),
        "sampleNameCn": FieldLabel("sample_name_cn", "样品名称"),
        "sampleModelCn": FieldLabel("sample_model_cn", "样品型号"),
        "sampleNo": FieldLabel("sample_no", "样品编号"),
        "terminalAuthorizationCustomer": FieldLabel("terminal_authorization_customer", "授权终端客户"),
        "salerPersonName": FieldLabel("saler_person_name", "负责销售"),
        "remark": FieldLabel("remark", "项目备注"),
    },
    enum_fields={
        "charge_bstatus": EnumField({1: "未转销售合同", 4: "已转销售合同", 5: "已收款", 0: "已作废"}),
        "order_description": EnumField({1: "需要", 2: "不需要"}),
        "order_status": EnumField({0: "未开单", 1: "已开单"}),
        "test_requirement": EnumField({"scene": "现场测试", "rectification": "案件整改/重测", "caseTest": "案件测试"}),
    },
)
