"""Module config: 付款申请列表 (FinCasPaymentApplyListAction)"""
from __future__ import annotations
from new_mcp_servers.core.config import EnumField, FieldLabel, FilterDef, ModuleConfig

_BASE_PATH = "/FinCasPaymentApplyListAction"

fin_cas_payment_apply = ModuleConfig(
    name="query_fincaspaymentapplylistaction",
    display_name="付款申请",
    description="查询付款申请列表。",
    endpoint=_BASE_PATH + "/listQuery",
    scope_endpoints={
        "default": _BASE_PATH + "/listQuery",
        "emc": _BASE_PATH + "/listQueryEmc",
        "expense": _BASE_PATH + "/listQueryExpense",
        "home": _BASE_PATH + "/listQueryFinCasPaymentApplyHome",
        "home2": _BASE_PATH + "/listQueryFinCasPaymentApplyHome2",
        "home3": _BASE_PATH + "/listQueryFinCasPaymentApplyHome3",
        "home4": _BASE_PATH + "/listQueryFinCasPaymentApplyHome4",
        "gen": _BASE_PATH + "/listQueryGeneralEmc",
        "dept": _BASE_PATH + "/listQueryMyDept",
        "mine": _BASE_PATH + "/listQueryMyPerson",
        "reliability": _BASE_PATH + "/listQueryReliability",
        "rf": _BASE_PATH + "/listQueryRf",
        "safety": _BASE_PATH + "/listQuerySafety",
    },
    extra_params=["include_raw"],
    filters=[
        FilterDef("advance_no", "order_no2", "预支编号", "like"),
        FilterDef("amt", "sum_amt", "金额", "="),
        FilterDef("applicant_name", "applicantName", "费用申请人", "like"),
        FilterDef("apply_status", "rstatus", "申请状态", "="),
        FilterDef("apply_type", "apply_type", "申请类别", "=", enums={10: "有发票报销付款", 20: "无发票报销付款", 30: "借款付款"}),
        FilterDef("approve_date_end", "approve_date", "审核日期止", "<=", is_date_range=True),
        FilterDef("bstatus", "bstatus", "报销状态", "=", enums={1: "未报销", 2: "已报销"}),
        FilterDef("contract_no", "sales_order_no", "合同编号", "like"),
        FilterDef("customer_name_cn", "customer_name_cn", "客户名称", "like"),
        FilterDef("department_id", "department_id", "申请部门", "="),
        FilterDef("description_of_expenditure_content", "fcpad.description_of_expenditure_content", "预支内容", "like"),
        FilterDef("end_time", "create_on", "创建日期止", "<=", is_date_range=True),
        FilterDef("expense_course", "expenseAccount", "支出科目", "like"),
        FilterDef("expense_type", "expenditureCategory", "支出类别", "like"),
        FilterDef("fast_search", "fastSearch", "快速搜索", "like"),
        FilterDef("offset_rstatus", "offset_rstatus", "还款/冲账状态", "=", enums={2: "已部分还款/冲账", 1: "已还款/冲账", 0: "未还款/未冲账", -1: "N/A"}),
        FilterDef("order_no", "order_no", "申请编号", "like"),
        FilterDef("pay_account_name", "account_name", "收款方", "like"),
        FilterDef("payment_status", "payment_status", "付款状态", "=", enums={10: "未付款", 20: "部分付款", 30: "已付款"}),
        FilterDef("receiver_name", "receiverName", "收款方(候选)", "like"),
        FilterDef("recorder_id", "personName", "制单人", "like"),
        FilterDef("remark", "remark", "备注", "like"),
        FilterDef("start_approve_date", "approve_date", "审核日期起", ">=", is_date_range=True),
        FilterDef("start_time", "create_on", "创建日期起", ">=", is_date_range=True),
        FilterDef("supplier_name", "supplier_name", "供应商", "like"),
        FilterDef("amt_local", "amtLocal", "人民币申请金额", "like"),
        FilterDef("approve_date_start", "approveDate", "审核日期起(候选)", ">=", is_date_range=True),
        FilterDef("create_on_end", "createOn", "创建日期止(候选)", "<=", is_date_range=True),
        FilterDef("create_on_start", "createOn", "创建日期起(候选)", ">=", is_date_range=True),
        FilterDef("expenditure_category", "expenditureCategory", "支出类别(候选)", "like"),
        FilterDef("expense_account", "expenseAccount", "支出科目(候选)", "like"),
        FilterDef("expense_item_type", "expenseItemType", "支出类别(枚举)", "=",
                  enums={"sd-certificate-a": "规费B/发证费", "sd-outsource": "外包", "sd-consumable": "其它耗材", "sd-other": "规费A"}),
        FilterDef("item_name", "itemName", "服务项目", "like"),
        FilterDef("order_no2", "orderNo2", "预支编号(候选)", "like"),
        FilterDef("payment_amt_local", "paymentAmtLocal", "已付款金额", "like"),
        FilterDef("person_name", "personName", "制单人(候选)", "like"),
        FilterDef("project_no", "projectNo", "案件号", "like"),
        FilterDef("receive_acctnumber", "receiveAcctnumber", "收款方账号", "like"),
        FilterDef("receive_bank_name", "receiveBankName", "收款方开户行", "like"),
        FilterDef("rstatus", "rstatus", "审核状态", "=", enums={0: "已作废", 1: "已审核", 2: "暂存", 3: "等待重新审批", 4: "审批中"}),
        FilterDef("sales_order_no", "salesOrderNo", "合同编号(候选)", "like"),
        FilterDef("sales_order_rstatus", "salesOrderRstatus", "合同审核状态", "=", enums={0: "已作废", 1: "已审核", 2: "暂存", 3: "等待重新审批", 4: "审批中"}),
        FilterDef("unpayment_amt_local", "unpaymentAmtLocal", "人民币待付款金额", "like"),
    ],
    field_labels={
        "orderNo": FieldLabel("order_no", "申请编号"),
        "createOn": FieldLabel("create_on", "申请日期"),
        "rstatus": FieldLabel("rstatus", "审核状态"),
        "salesOrderRstatus": FieldLabel("sales_order_rstatus", "合同审核状态"),
        "approveDate": FieldLabel("approve_date", "审核日期"),
        "personName": FieldLabel("person_name", "制单人"),
        "salesOrderNo": FieldLabel("sales_order_no", "合同编号"),
        "applicantName": FieldLabel("applicant_name", "费用申请人"),
        "departmentName": FieldLabel("department_name", "申请部门"),
        "orderNo2": FieldLabel("order_no2", "预支编号"),
        "applyType": FieldLabel("apply_type", "申请类别"),
        "customerNameCn": FieldLabel("customer_name_cn", "客户名称"),
        "projectNo": FieldLabel("project_no", "案件号"),
        "descriptionOfExpenditureContent": FieldLabel("description_of_expenditure_content", "预支内容"),
        "amt": FieldLabel("amt", "申请金额"),
        "supplierName": FieldLabel("supplier_name", "供应商/收款方"),
        "expenditureCategory": FieldLabel("expenditure_category", "支出类别"),
        "paymentStatus": FieldLabel("payment_status", "付款状态"),
        "itemName": FieldLabel("item_name", "服务项目"),
        "amtLocal": FieldLabel("amt_local", "人民币申请金额"),
        "expenseAccount": FieldLabel("expense_account", "支出科目"),
        "receiverName": FieldLabel("receiver_name", "收款方"),
        "receiveAcctnumber": FieldLabel("receive_acctnumber", "收款方账号"),
        "bstatus": FieldLabel("bstatus", "报销状态"),
        "paymentAmtLocal": FieldLabel("payment_amt_local", "人民币已付款金额"),
        "receiveBankName": FieldLabel("receive_bank_name", "收款方开户行"),
        "remark": FieldLabel("remark", "备注"),
        "offsetRstatus": FieldLabel("offset_rstatus", "还款/冲账状态"),
        "expenseItemType": FieldLabel("expense_item_type", "支出类别"),
        "unpaymentAmtLocal": FieldLabel("unpayment_amt_local", "人民币待付款金额"),
    },
    enum_fields={
        "apply_type": EnumField({10: "有发票报销付款", 20: "无发票报销付款", 30: "借款付款"}),
        "bstatus": EnumField({1: "未报销", 2: "已报销"}),
        "expense_item_type": EnumField({"sd-certificate-a": "规费B/发证费", "sd-outsource": "外包", "sd-consumable": "其它耗材", "sd-other": "规费A"}),
        "offset_rstatus": EnumField({2: "已部分还款/冲账", 1: "已还款/冲账", 0: "未还款/未冲账", -1: "N/A"}),
        "payment_status": EnumField({10: "未付款", 20: "部分付款", 30: "已付款"}),
        "rstatus": EnumField({0: "已作废", 1: "已审核", 2: "暂存", 3: "等待重新审批", 4: "审批中"}),
        "sales_order_rstatus": EnumField({0: "已作废", 1: "已审核", 2: "暂存", 3: "等待重新审批", 4: "审批中"}),
    },
)
