"""Module config: 采购列表 (PurPurchaseListAction)"""
from __future__ import annotations
from new_mcp_servers.core.config import EnumField, FieldLabel, FilterDef, ModuleConfig

_BASE_PATH = "/PurPurchaseListAction"

pur_purchase = ModuleConfig(
    name="query_purpurchaselistaction",
    display_name="采购列表",
    description="查询采购列表。",
    endpoint=_BASE_PATH + "/listQuery",
    scope_endpoints={
        "default": _BASE_PATH + "/listQuery",
        "listquerybysupplierid": _BASE_PATH + "/listQueryBySupplierId",
        "listquerymaterial": _BASE_PATH + "/listQueryMaterial",
        "listquerysubcontract": _BASE_PATH + "/listQuerySubcontract",
    },
    scope_svars={
        "default": {"show_all": "1", "modularType": "modular_type", "operation": "operation"},
    },
    extra_params=["include_raw"],
    filters=[
        FilterDef("accept_status", "pp.accept_status", "验收状态", "=", enums={0: "未验收", 1: "已验收"}),
        FilterDef("arrive_status", "pp.arrive_status", "到货状态", "=", enums={0: "未到货", 2: "部分到货", 1: "全部到货", 3: "未开始服务"}),
        FilterDef("assess_status", "pp.assess_status", "采购评价", "="),
        FilterDef("bstatus", "pp.bstatus", "采购状态", "="),
        FilterDef("bstatus_payment", "pp.bstatus_payment", "付款状态", "="),
        FilterDef("consignor_name_cn", "consignorNameCn", "合同方", "like"),
        FilterDef("department_id", "ad.id", "部门", "="),
        FilterDef("fast_search", "fastSearch", "快速搜索", "like"),
        FilterDef("invoice_status", "pp.invoice_status", "开票状态", "="),
        FilterDef("manager_category", "pp.manager_category", "管理类别", "="),
        FilterDef("order_no", "orderNo", "采购编号", "like"),
        FilterDef("purchase_desc", "purchaseDesc", "采购内容", "like"),
        FilterDef("source_biz_no", "txnCoreNo", "开案号", "like"),
        FilterDef("store_status", "pp.store_status", "资产入库", "="),
        FilterDef("supplier", "pp.supplier_name", "供应商", "like"),
        FilterDef("supplier_name", "pp.supplier_name", "供应商名称", "like"),
        FilterDef("actuality_settlement_date_start", "actualitySettlementDate", "实际结款日期起", ">=", is_date_range=True),
        FilterDef("actuality_settlement_date_end", "actualitySettlementDate", "实际结款日期止", "<=", is_date_range=True),
        FilterDef("amt_with_tax", "amtWithTax", "总计金额", "like"),
        FilterDef("complete_invoice_date_start", "completeInvoiceDate", "收齐票日期起", ">=", is_date_range=True),
        FilterDef("complete_invoice_date_end", "completeInvoiceDate", "收齐票日期止", "<=", is_date_range=True),
        FilterDef("invoiced_amt", "invoicedAmt", "已开票金额", "like"),
        FilterDef("latest_invoice_date_start", "latestInvoiceDate", "最新收票日期起", ">=", is_date_range=True),
        FilterDef("latest_invoice_date_end", "latestInvoiceDate", "最新收票日期止", "<=", is_date_range=True),
        FilterDef("latest_payment_date_start", "latestPaymentDate", "最新付款日期起", ">=", is_date_range=True),
        FilterDef("latest_payment_date_end", "latestPaymentDate", "最新付款日期止", "<=", is_date_range=True),
        FilterDef("order_date_start", "orderDate", "采购日期起", ">=", is_date_range=True),
        FilterDef("order_date_end", "orderDate", "采购日期止", "<=", is_date_range=True),
        FilterDef("paid_amt", "paidAmt", "已付款金额", "like"),
        FilterDef("person_name", "personName", "申请人", "like"),
        FilterDef("purchase_contract_no", "purchaseContractNo", "采购合同编号", "like"),
        FilterDef("saler_name", "salerName", "负责业务", "like"),
        FilterDef("uninvoiced_amt", "uninvoicedAmt", "剩余应开票金额", "like"),
        FilterDef("unpaid_amt", "unpaidAmt", "剩余应付款金额", "like"),
    ],
    field_labels={
        "orderNo": FieldLabel("order_no", "采购编号"),
        "managerCategory": FieldLabel("manager_category", "管理类别"),
        "orderDate": FieldLabel("order_date", "采购日期"),
        "txnCoreNo": FieldLabel("txn_core_no", "开案号"),
        "personName": FieldLabel("person_name", "申请人"),
        "salerName": FieldLabel("saler_name", "负责业务"),
        "purchaseContractNo": FieldLabel("purchase_contract_no", "采购合同编号"),
        "consignorNameCn": FieldLabel("consignor_name_cn", "合同方"),
        "supplierName": FieldLabel("supplier_name", "供应商名称"),
        "departmentName": FieldLabel("department_name", "负责实验室/部门"),
        "purchaseDesc": FieldLabel("purchase_desc", "采购内容描述"),
        "amtWithTax": FieldLabel("amt_with_tax", "总计金额"),
        "bstatusPayment": FieldLabel("bstatus_payment", "付款状态"),
        "paidAmt": FieldLabel("paid_amt", "已经付款金额"),
        "unpaidAmt": FieldLabel("unpaid_amt", "剩余应付款金额"),
        "invoicedAmt": FieldLabel("invoiced_amt", "已经开票金额"),
        "uninvoicedAmt": FieldLabel("uninvoiced_amt", "剩余应开票金额"),
        "bstatus": FieldLabel("bstatus", "采购状态"),
        "invoiceStatus": FieldLabel("invoice_status", "开票状态"),
        "latestPaymentDate": FieldLabel("latest_payment_date", "最新付款日期"),
        "actualitySettlementDate": FieldLabel("actuality_settlement_date", "实际结款日期"),
        "latestInvoiceDate": FieldLabel("latest_invoice_date", "最新收票日期"),
        "completeInvoiceDate": FieldLabel("complete_invoice_date", "收齐票日期"),
        "arriveStatus": FieldLabel("arrive_status", "服务/到货状态"),
        "acceptStatus": FieldLabel("accept_status", "验收状态"),
        "storeStatus": FieldLabel("store_status", "资产入库"),
        "assessStatus": FieldLabel("assess_status", "采购评价"),
    },
    enum_fields={
        "accept_status": EnumField({0: "未验收", 1: "已验收"}),
        "arrive_status": EnumField({0: "未到货", 2: "部分到货", 1: "全部到货", 3: "未开始服务"}),
    },
)
