"""
Module config: 销售合同/订单列表 (SdSalesOrderListAction)

完整迁移自 ``mcp_servers/sd_sales_order_mcp/tools.py``。
"""

from __future__ import annotations

from new_mcp_servers.core.config import EnumField, FieldLabel, FilterDef, ModuleConfig

_BASE_PATH = "/SdSalesOrderListAction"

sales_order = ModuleConfig(
    name="query_sales_order_list",
    display_name="销售合同/订单",
    description="查询销售合同/销售订单列表。通过 scope/view 路由到 15 个后端列表接口。返回 count、columns、data。",
    endpoint=_BASE_PATH + "/listQuery",
    scope_endpoints={
        "default": _BASE_PATH + "/listQuery",
        "gen": _BASE_PATH + "/listQuery",
        "approved_uninvoiced": _BASE_PATH + "/listQueryApprovedUninvoiced",
        "cancel": _BASE_PATH + "/listQueryCancel",
        "dept": _BASE_PATH + "/listQueryDept",
        "fin": _BASE_PATH + "/listQueryFin",
        "final": _BASE_PATH + "/listQueryFinal",
        "fin_my": _BASE_PATH + "/listQueryFinMY",
        "offsite_trial": _BASE_PATH + "/listQueryForOffsiteTrial",
        "invoice": _BASE_PATH + "/listQueryInvoice",
        "my": _BASE_PATH + "/listQueryMy",
        "my_unreceive": _BASE_PATH + "/listQueryMyUnReceive",
        "top10": _BASE_PATH + "/listQueryTop10SaleAmt",
        "underway": _BASE_PATH + "/listQueryUnderway",
        "unpaid": _BASE_PATH + "/listQueryUnpaid",
    },
    scope_svars={
        "default": {"customerType": 1, "operation": "operation"},
        "gen": {"bstatusProject": 20, "dcProjectEmergencyList": True},
        "my": {"customerType": 3},
        "offsite_trial": {"customerType": 1, "modularType": "modularType"},
    },
    scope_datatype_defaults={
        "default": "Last30days",
        "gen": "pendingCaseView",
        "approved_uninvoiced": "Last30days",
        "dept": "Last30days",
        "offsite_trial": "Last30days",
        "my": "Last30days",
    },
    extra_params=["include_raw"],
    filters=[
        # ── 核心筛选 ──
        FilterDef("sales_order_no", "sso.sales_order_no", "销售合同号", "like"),
        FilterDef("customer_name", "ac.CUSTOMER_NAME_CN", "客户名称", "like"),
        FilterDef("customer_name_cn", "ac.CUSTOMER_NAME_CN", "客户名称(备)", "like"),
        FilterDef("customer_short_name", "ac.CUSTOMER_NAME_CN", "客户简称", "like"),
        FilterDef("bstatus", "sso.bstatus", "业务状态", "=",
                  enums={20: "未开案", 30: "案件进行中", 40: "结案收款中", 45: "结案已收款", 50: "结束", 60: "取消"}),
        FilterDef("rstatus", "sso.rstatus", "审核状态", "=",
                  enums={0: "已作废", 1: "已审核", 2: "暂存", 3: "等待重新审批", 4: "审批中"}),
        FilterDef("invoice_status", "sso.invoice_status", "开票状态", "=",
                  enums={20: "未开票", 30: "已部分开票", 50: "开齐票", 40: "不开票"}),
        FilterDef("bstatus_receive", "sso.bstatus_receive", "收款状态", "=",
                  enums={20: "未收款", 30: "已收部分款", 50: "结清"}),
        FilterDef("bstatus_attachment", "sso.bstatus_attachment", "附件状态", "=",
                  enums={20: "未上传", 30: "已上传", 40: "已确认"}),
        FilterDef("bstatus_project", "sso.bstatus_project", "开案状态", "=",
                  enums={20: "未开案", 25: "未开始", 30: "案件进行中", 40: "试验完成报告未出", 45: "试验完成报告已出", 50: "结案", 55: "异常"}),
        FilterDef("contract_status", "sso.bstatus", "合同状态", "=",
                  enums={20: "未开案", 30: "案件进行中", 40: "结案收款中", 45: "结案已收款", 50: "结束", 60: "取消"}),
        FilterDef("sales_order_type", "sso.bill_type_id", "合同类别", "="),
        FilterDef("fast_search", "fastSearch", "快速搜索", "like"),
        FilterDef("dept", "ad.department_name", "销售部门", "like"),
        FilterDef("sale_dept", "ad.department_name", "销售部门(备)", "like"),
        FilterDef("sale_person", "ap.PERSON_NAME", "负责销售", "like"),
        FilterDef("sales_name", "ap.PERSON_NAME", "销售名", "like"),
        FilterDef("sales_person", "ap.person_name", "销售人员", "like"),
        FilterDef("person_id", "ap.person_name", "人员", "like"),
        FilterDef("delivery_specialist", "ap2.PERSON_NAME", "交付专员", "like"),
        FilterDef("engineer_name", "engineerName", "工程师", "like"),
        FilterDef("department_id", "ad.department_name", "部门ID", "like"),
        FilterDef("organization_name", "ao.organization_name", "组织名", "like"),
        FilterDef("sale_dept_name", "ad.department_name", "销售部门名", "like"),
        # ── 金额 ──
        FilterDef("amt", "sso.amt_with_tax_local", "金额", "="),
        FilterDef("contract_amount", "sso.amt_with_tax_local", "合同金额", "="),
        FilterDef("invoiced_amt", "sso.invoiced_amt", "已开票金额", "like"),
        # ── 日期范围 ──
        FilterDef("create_on", "createOn", "创建日期", "="),
        FilterDef("create_on_start", "sso.create_on", "创建日期起", ">=", is_date_range=True),
        FilterDef("create_on_end", "sso.create_on", "创建日期止", "<=", is_date_range=True),
        FilterDef("sales_date_start", "sso.sales_date", "报价日期起", ">=", is_date_range=True),
        FilterDef("sales_date_end", "sso.sales_date", "报价日期止", "<=", is_date_range=True),
        FilterDef("approve_date_start", "sso.approve_date", "审批日期起", ">=", is_date_range=True),
        FilterDef("approve_date_end", "sso.approve_date", "审批日期止", "<=", is_date_range=True),
        FilterDef("start_date_start", "sso.start_date", "开案日期起", ">=", is_date_range=True),
        FilterDef("start_date_end", "sso.start_date", "开案日期止", "<=", is_date_range=True),
        FilterDef("actuality_end_date_start", "sso.actuality_end_date", "结案日期起", ">=", is_date_range=True),
        FilterDef("actuality_end_date_end", "sso.actuality_end_date", "结案日期止", "<=", is_date_range=True),
        FilterDef("actuality_finish_date_start", "sso.actuality_finish_date", "结束日期起", ">=", is_date_range=True),
        FilterDef("actuality_finish_date_end", "sso.actuality_finish_date", "结束日期止", "<=", is_date_range=True),
        FilterDef("cancel_create_on", "ssorh.approve_on", "取消创建日期起", ">=", is_date_range=True),
        FilterDef("cancel_create_on_end", "ssorh.approve_on", "取消创建日期止", "<=", is_date_range=True),
        FilterDef("kpi_grant_date_start", "sso.kpi_grant_date", "KPI发放日期起", ">=", is_date_range=True),
        FilterDef("kpi_grant_date_end", "sso.kpi_grant_date", "KPI发放日期止", "<=", is_date_range=True),
        FilterDef("receive_create_on", "sso.actuality_settlement_date", "收款日期起", ">=", is_date_range=True),
        FilterDef("receive_create_on_end", "sso.actuality_settlement_date", "收款日期止", "<=", is_date_range=True),
        FilterDef("receive_latest_create_on", "sso.latest_payment_date", "最新收款日期起", ">=", is_date_range=True),
        FilterDef("receive_latest_create_on_end", "sso.latest_payment_date", "最新收款日期止", "<=", is_date_range=True),
        FilterDef("expense_latest_create_on", "sso.latest_expense_date", "最新付款日期起", ">=", is_date_range=True),
        FilterDef("expense_latest_create_on_end", "sso.latest_expense_date", "最新付款日期止", "<=", is_date_range=True),
        FilterDef("order_date_start", "fai.order_date", "订单日期起", ">=", is_date_range=True),
        FilterDef("order_date_end", "fai.order_date", "订单日期止", "<=", is_date_range=True),
        FilterDef("net_profits_ratio_end", "sso.net_profits_ratio", "净利润率上限", "<="),
        # ── 样品/项目 ──
        FilterDef("sample_name_cn", "sso.sample_name_cn", "样品名称", "like"),
        FilterDef("sample_model_cn", "sso.sample_model_cn", "样品型号", "like"),
        FilterDef("service_item", "sso.service_item_desc", "服务项目", "like"),
        FilterDef("terminal_authorization_customer", "sso.terminal_authorization_customer_name", "终端客户", "like"),
        # ── 候选 filter（后端响应列反推） ──
        FilterDef("abd_customer_customer_name_cn", "abdCustomer.customerNameCn", "客户名(候选)", "like"),
        FilterDef("sales_dept_name", "ad.department_name", "销售部门(候选)", "like"),
        FilterDef("actuality_settlement_date_start", "actualitySettlementDate", "实际结算日期起", ">=", is_date_range=True),
        FilterDef("actuality_settlement_date_end", "actualitySettlementDate", "实际结算日期止", "<=", is_date_range=True),
        FilterDef("actually_expenditure_amt", "actuallyExpenditureAmt", "实际支出", "like"),
        FilterDef("actually_expenditure_amt_local", "actuallyExpenditureAmtLocal", "实际支出本币", "like"),
        FilterDef("actually_net_price_local", "actuallyNetPriceLocal", "实际净价本币", "like"),
        FilterDef("amt_with_tax", "amtWithTax", "含税金额", "like"),
        FilterDef("amt_with_tax_local", "amtWithTaxLocal", "含税金额本币", "like"),
        FilterDef("bill_type_id", "billTypeId", "单据类型ID", "="),
        FilterDef("bstatus_kpi", "bstatusKpi", "绩效状态", "=",
                  enums={20: "未发", 50: "已发"}),
        FilterDef("cancel_date_start", "cancelDate", "取消日期起", ">=", is_date_range=True),
        FilterDef("cancel_date_end", "cancelDate", "取消日期止", "<=", is_date_range=True),
        FilterDef("cancel_person_name", "cancelPersonName", "取消人", "like"),
        FilterDef("complete_invoice_date_start", "completeInvoiceDate", "完成开票日期起", ">=", is_date_range=True),
        FilterDef("complete_invoice_date_end", "completeInvoiceDate", "完成开票日期止", "<=", is_date_range=True),
        FilterDef("create_person_name", "createPersonName", "创建人", "like"),
        FilterDef("currency_name", "currencyName", "币种", "like"),
        FilterDef("deduction_amt_local", "deductionAmtLocal", "扣减金额本币", "like"),
        FilterDef("expect_expenditure_amt_local", "expectExpenditureAmtLocal", "预计支出本币", "like"),
        FilterDef("invoice_no", "invoiceNo", "发票号", "like"),
        FilterDef("invoiced_amt_local", "invoicedAmtLocal", "已开票本币", "like"),
        FilterDef("latest_expense_date_start", "latestExpenseDate", "最新付款日期起", ">=", is_date_range=True),
        FilterDef("latest_expense_date_end", "latestExpenseDate", "最新付款日期止", "<=", is_date_range=True),
        FilterDef("latest_invoice_date_start", "latestInvoiceDate", "最新开票日期起", ">=", is_date_range=True),
        FilterDef("latest_invoice_date_end", "latestInvoiceDate", "最新开票日期止", "<=", is_date_range=True),
        FilterDef("latest_payment_date_start", "latestPaymentDate", "最新收款日期起", ">=", is_date_range=True),
        FilterDef("latest_payment_date_end", "latestPaymentDate", "最新收款日期止", "<=", is_date_range=True),
        FilterDef("net_profits_ratio", "netProfitsRatio", "净利润率", "like"),
        FilterDef("net_profits_ratio_local", "netProfitsRatioLocal", "净利润率本币", "like"),
        FilterDef("overdue_settlement", "overdueSettlement", "逾期结算", "like"),
        FilterDef("person_name", "personName", "人名", "like"),
        FilterDef("receivable_amt", "receivableAmt", "应收金额", "like"),
        FilterDef("receivable_amt_local", "receivableAmtLocal", "应收金额本币", "like"),
        FilterDef("received_amt", "receivedAmt", "已收金额", "like"),
        FilterDef("received_amt_local", "receivedAmtLocal", "已收金额本币", "like"),
        FilterDef("remark", "remark", "内部备注", "like"),
        FilterDef("request_invoice_type", "requestInvoiceType", "开票类型", "="),
        FilterDef("request_invoiced_amt", "requestInvoicedAmt", "已申请开票金额", "like"),
        FilterDef("revise_desc", "reviseDesc", "修订说明", "like"),
        FilterDef("sale_amt", "saleAmt", "销售金额", "like"),
        FilterDef("service_item_desc", "serviceItemDesc", "项目描述", "like"),
        FilterDef("sum_certificate_amt_local", "sumCertificateAmtLocal", "规费总计", "like"),
        FilterDef("sum_consumable_amt_local", "sumConsumableAmtLocal", "耗材总计", "like"),
        FilterDef("sum_net_price2_local", "sumNetPrice2Local", "净价2总计", "like"),
        FilterDef("sum_other_amt_local", "sumOtherAmtLocal", "其他支出总计", "like"),
        FilterDef("sum_outsource_amt_local", "sumOutsourceAmtLocal", "外包费总计", "like"),
        FilterDef("tax_amt_local", "taxAmtLocal", "税费", "like"),
        FilterDef("terminal_authorization_customer_name", "terminalAuthorizationCustomerName", "终端客户名", "like"),
        FilterDef("uninvoiced_amt_local", "uninvoicedAmtLocal", "未开票本币", "like"),
    ],
    field_labels={
        "salesOrderNo": FieldLabel("sales_order_no", "销售合同号"),
        "rstatus": FieldLabel("rstatus", "审核状态"),
        "bstatus": FieldLabel("bstatus", "业务状态"),
        "invoiceStatus": FieldLabel("invoice_status", "开票状态"),
        "bstatusReceive": FieldLabel("bstatus_receive", "收款状态"),
        "createOn": FieldLabel("create_on", "合同日期"),
        "salesDate": FieldLabel("sales_date", "报价/开单日期"),
        "startDate": FieldLabel("start_date", "开案日期"),
        "actualityFinishDate": FieldLabel("actuality_finish_date", "结束日期"),
        "customerNameCn": FieldLabel("customer_name_cn", "客户名称"),
        "terminalAuthorizationCustomerName": FieldLabel("terminal_authorization_customer_name", "授权方/终端客"),
        "serviceItemDesc": FieldLabel("service_item_desc", "合同描述"),
        "sampleNameCn": FieldLabel("sample_name_cn", "样品名称"),
        "sampleModelCn": FieldLabel("sample_model_cn", "样品型号"),
        "amtWithTaxLocal": FieldLabel("amt_with_tax_local", "人民币合同金额"),
        "personName": FieldLabel("person_name", "销售"),
        "deliverySpecialist": FieldLabel("delivery_specialist", "交付专员"),
        "departmentName": FieldLabel("department_name", "部门"),
        "remark": FieldLabel("remark", "内部备注"),
        "receivedAmtLocal": FieldLabel("received_amt_local", "人民币已收"),
        "receivableAmtLocal": FieldLabel("receivable_amt_local", "人民币剩余应收"),
        "requestInvoicedAmt": FieldLabel("request_invoiced_amt", "已申请金额"),
        "invoicedAmt": FieldLabel("invoiced_amt", "已开票"),
        "actualityEndDate": FieldLabel("actuality_end_date", "结案时间"),
        "sumCertificateAmtLocal": FieldLabel("sum_certificate_amt_local", "规费/发证费总计"),
        "sumOutsourceAmtLocal": FieldLabel("sum_outsource_amt_local", "外包费总计"),
        "sumConsumableAmtLocal": FieldLabel("sum_consumable_amt_local", "耗材总计"),
        "sumOtherAmtLocal": FieldLabel("sum_other_amt_local", "其它支出总计"),
        "taxAmtLocal": FieldLabel("tax_amt_local", "税费"),
        "sumNetPrice2Local": FieldLabel("sum_net_price2_local", "净价2总计"),
        "netProfitsRatio": FieldLabel("net_profits_ratio", "净利润率"),
        "expectExpenditureAmtLocal": FieldLabel("expect_expenditure_amt_local", "预计支出"),
        "actuallyExpenditureAmtLocal": FieldLabel("actually_expenditure_amt_local", "实际支出"),
        "latestInvoiceDate": FieldLabel("latest_invoice_date", "最新开票日期"),
        "latestPaymentDate": FieldLabel("latest_payment_date", "最新收款日期"),
        "latestExpenseDate": FieldLabel("latest_expense_date", "最新付款日期"),
    },
    enum_fields={
        "bstatus": EnumField({20: "未开案", 30: "案件进行中", 40: "结案收款中", 45: "结案已收款", 50: "结束", 60: "取消"}),
        "bstatus_receive": EnumField({20: "未收款", 30: "已收部分款", 50: "结清"}),
        "invoice_status": EnumField({20: "未开票", 30: "已部分开票", 50: "开齐票", 40: "不开票"}),
        "rstatus": EnumField({0: "已作废", 1: "已审核", 2: "暂存", 3: "等待重新审批", 4: "审批中"}),
    },
)
