"""Module config: 服务项目列表 (SdServiceItemListAction)"""
from __future__ import annotations
from new_mcp_servers.core.config import EnumField, FieldLabel, FilterDef, ModuleConfig

_BASE_PATH = "/SdServiceItemListAction"

sd_service_item = ModuleConfig(
    name="query_sdserviceitemlistaction",
    display_name="服务项目",
    description="查询服务项目列表。",
    endpoint=_BASE_PATH + "/listQuery",
    scope_endpoints={"default": _BASE_PATH + "/listQuery"},
    extra_params=["include_raw"],
    filters=[
        FilterDef("country", "country", "国别", "like"),
        FilterDef("dept", "ssi.responsible_dept_by", "负责部门", "="),
        FilterDef("fast_search", "fastSearch", "快速搜索", "like"),
        FilterDef("item_category", "itemCategory", "类别", "like"),
        FilterDef("item_category2", "itemCategory2", "领域类别", "like"),
        FilterDef("item_name", "itemName", "服务项目名称", "like"),
        FilterDef("item_no", "itemNo", "编号", "like"),
        FilterDef("product_category", "productCategory", "产品类别", "like"),
        FilterDef("product_desc", "productDesc", "产品描述", "like"),
        FilterDef("rstatus", "ssi.rstatus", "状态", "=",
                  enums={1: "审核", 2: "暂存", 0: "作废", 3: "等待重新审批", 4: "提交"}),
        FilterDef("test_standard", "testStandard", "依据标准", "like"),
        FilterDef("certificate_amt", "certificateAmt", "规费支出", "like"),
        FilterDef("consumable_amt", "consumableAmt", "耗材支出", "like"),
        FilterDef("electric_charge_amt", "electricChargeAmt", "电费支出", "like"),
        FilterDef("equipment_depreciation_amt", "equipmentDepreciationAmt", "设备折旧", "like"),
        FilterDef("flag_fall_price", "flagFallPrice", "最低起步价", "="),
        FilterDef("gross_profit", "grossProfit", "项目毛利", "like"),
        FilterDef("information_requirement", "informationRequirement", "资料要求", "like"),
        FilterDef("new_service_duration", "newServiceDuration", "服务周期", "="),
        FilterDef("other_amt", "otherAmt", "其他支出", "like"),
        FilterDef("outsource_amt", "outsourceAmt", "外包支出", "like"),
        FilterDef("remark", "remark", "备注", "like"),
        FilterDef("remark1", "remark1", "内部备注", "like"),
        FilterDef("sample_requirement", "sampleRequirement", "样品需求", "like"),
        FilterDef("unit_name", "unitName", "计价单位", "like"),
        FilterDef("unit_price", "unitPrice", "RMB标准价格", "="),
        FilterDef("us_unit_price", "usUnitPrice", "美元标准价格", "="),
    ],
    field_labels={
        "itemNo": FieldLabel("item_no", "编号"),
        "rstatus": FieldLabel("rstatus", "状态"),
        "itemName": FieldLabel("item_name", "服务项目名称"),
        "itemCategory": FieldLabel("item_category", "类别"),
        "responsibleDeptName": FieldLabel("responsible_dept_name", "负责部门"),
        "productCategory": FieldLabel("product_category", "产品类别"),
        "itemCategory2": FieldLabel("item_category2", "领域类别"),
        "country": FieldLabel("country", "国别"),
        "testStandard": FieldLabel("test_standard", "依据标准"),
        "usUnitPrice": FieldLabel("us_unit_price", "美元标准价格"),
        "productDesc": FieldLabel("product_desc", "产品描述"),
        "unitName": FieldLabel("unit_name", "计价单位"),
        "newServiceDuration": FieldLabel("new_service_duration", "服务周期"),
        "unitPrice": FieldLabel("unit_price", "RMB标准价格"),
        "flagFallPrice": FieldLabel("flag_fall_price", "最低起步价"),
        "certificateAmt": FieldLabel("certificate_amt", "规费支出"),
        "outsourceAmt": FieldLabel("outsource_amt", "外包支出"),
        "consumableAmt": FieldLabel("consumable_amt", "耗材支出"),
        "electricChargeAmt": FieldLabel("electric_charge_amt", "电费支出"),
        "equipmentDepreciationAmt": FieldLabel("equipment_depreciation_amt", "设备折旧"),
        "otherAmt": FieldLabel("other_amt", "其他支出"),
        "grossProfit": FieldLabel("gross_profit", "项目毛利"),
        "informationRequirement": FieldLabel("information_requirement", "资料要求"),
        "sampleRequirement": FieldLabel("sample_requirement", "样品需求"),
        "remark1": FieldLabel("remark1", "内部备注"),
        "remark": FieldLabel("remark", "备注"),
    },
    enum_fields={
        "rstatus": EnumField({1: "审核", 2: "暂存", 0: "作废", 3: "等待重新审批", 4: "提交"}),
    },
)
