"""Module config: 供应商列表 (AbdSupplierListAction)"""
from __future__ import annotations
from new_mcp_servers.core.config import EnumField, FieldLabel, FilterDef, ModuleConfig

_BASE_PATH = "/AbdSupplierListAction"

supplier = ModuleConfig(
    name="query_supplier_list",
    display_name="供应商列表",
    description="查询供应商列表。",
    endpoint=_BASE_PATH + "/listQuery",
    scope_endpoints={
        "default": _BASE_PATH + "/listQuery",
        "select": _BASE_PATH + "/listQuerySelect",
        "payment": _BASE_PATH + "/supplierPaymentQuery",
        "qm": _BASE_PATH + "/listQuery",
        "dept": _BASE_PATH + "/listQuery",
        "my": _BASE_PATH + "/listQuery",
    },
    scope_svars={
        "default": {"operation": "operation"},
        "qm": {"scope": "qm"},
        "dept": {"show_dept": "1"},
        "my": {"operation": "My"},
    },
    extra_params=["include_raw"],
    filters=[
        FilterDef("dept", "asu.filing_department_id", "部门", "="),
        FilterDef("description", "description", "服务项目", "like"),
        FilterDef("fast_search", "fastSearch", "快速搜索", "like"),
        FilterDef("person", "p.PERSON_NAME", "负责人", "like"),
        FilterDef("rstatus", "asu.bstatus", "状态", "=", enums={1: "合作中", 2: "暂停合作", 3: "黑名单", 4: "待审核", 5: "审核中"}),
        FilterDef("rstatus2", "asu.rstatus", "记录状态", "=", enums={0: "已作废", 1: "已审核", 2: "暂存", 3: "等待重新审批", 4: "审批中"}),
        FilterDef("supplier_grade_id", "supplierGradeId", "供应商等级", "="),
        FilterDef("supplier_manage_category", "asu.manage_category", "管理分类", "="),
        FilterDef("supplier_name", "supplierName", "供应商名称", "like"),
        FilterDef("supplier_no", "supplierNo", "供应商编号", "like"),
        FilterDef("supplier_type_id", "asu.supplier_type_id", "供应商类别", "="),
        FilterDef("address", "address", "地址", "like"),
        FilterDef("amt_local", "amtLocal", "付款总计", "like"),
        FilterDef("annual_review_date_start", "annualReviewDate", "年审日期起", ">=", is_date_range=True),
        FilterDef("annual_review_date_end", "annualReviewDate", "年审日期止", "<=", is_date_range=True),
        FilterDef("annual_review_status", "annualReviewStatus", "年审状态", "=", enums={10: "有效", 20: "过期"}),
        FilterDef("area_name", "areaName", "国家或地区", "like"),
        FilterDef("bstatus", "bstatus", "业务状态", "="),
        FilterDef("contact_name", "contactName", "联系人", "like"),
        FilterDef("create_on_start", "createOn", "创建日期起", ">=", is_date_range=True),
        FilterDef("create_on_end", "createOn", "创建日期止", "<=", is_date_range=True),
        FilterDef("evaluation_date_start", "evaluationDate", "评估日期起", ">=", is_date_range=True),
        FilterDef("evaluation_date_end", "evaluationDate", "评估日期止", "<=", is_date_range=True),
        FilterDef("filing_date_start", "filingDate", "备案日期起", ">=", is_date_range=True),
        FilterDef("filing_date_end", "filingDate", "备案日期止", "<=", is_date_range=True),
        FilterDef("last_collaboration_date_start", "lastCollaborationDate", "最近合作日期起", ">=", is_date_range=True),
        FilterDef("last_collaboration_date_end", "lastCollaborationDate", "最近合作日期止", "<=", is_date_range=True),
        FilterDef("mobile_telephone", "mobileTelephone", "手机", "like"),
        FilterDef("person_name", "personName", "联系人", "like"),
        FilterDef("tax_ratio", "taxRatio", "税率", "like"),
    ],
    field_labels={
        "supplierNo": FieldLabel("supplier_no", "供应商编号"),
        "supplierName": FieldLabel("supplier_name", "供应商名称"),
        "amtLocal": FieldLabel("amt_local", "付款总计"),
        "supplierTypeName": FieldLabel("supplier_type_name", "供应商类别"),
        "description": FieldLabel("description", "服务项目"),
        "supplierGradeName": FieldLabel("supplier_grade_name", "供应商等级"),
        "areaName": FieldLabel("area_name", "国家或地区"),
        "address": FieldLabel("address", "地址"),
        "contactName": FieldLabel("contact_name", "联系人"),
        "mobileTelephone": FieldLabel("mobile_telephone", "手机"),
        "filingDate": FieldLabel("filing_date", "备案日期"),
        "evaluationDate": FieldLabel("evaluation_date", "评估日期"),
        "createOn": FieldLabel("create_on", "创建日期"),
        "lastCollaborationDate": FieldLabel("last_collaboration_date", "最近合作日期"),
        "annualReviewDate": FieldLabel("annual_review_date", "年审日期"),
        "annualReviewStatus": FieldLabel("annual_review_status", "年审状态"),
        "departmentName": FieldLabel("department_name", "部门"),
        "taxRatio": FieldLabel("tax_ratio", "税率"),
        "personName": FieldLabel("person_name", "负责人"),
        "bstatus": FieldLabel("bstatus", "业务状态"),
        "rstatus": FieldLabel("rstatus", "记录状态"),
    },
    enum_fields={
        "bstatus": EnumField({1: "合作中", 2: "暂停合作", 3: "黑名单", 4: "待审核", 5: "审核中"}),
        "rstatus": EnumField({0: "已作废", 1: "已审核", 2: "暂存", 3: "等待重新审批", 4: "审批中"}),
    },
)
